set-option -g status-right '%Y-%m-%d %A %H:%M'

# session > window > pane
set-option -g base-index 1
set-window-option -g pane-base-index 1

set-option -g mouse on

set-option -s set-clipboard on

set -s extended-keys on

