name: Format Neovim configs

on:
  push:
    branches:
      - main
    paths:
      - "nvim/**"
  pull_request:
    paths:
      - "nvim/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        working-directory: nvim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1

      - name: format-nvim
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.1.0
          args: --check nvim
